
# Parser_Lefffinterpreteur_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'VAL SEP NUM A : \'[\' B \']\'  B : C \',\' B  B : C  C : VAL \'=\' D  D : "\'" VAL SEP NUM E "\'"  D : VAL  E : \'<\' F \'>\'  F : G \',\' F  F : G  G : VAL \':\' H  H : I  H : VAL  I : \'(\' J \')\'  J : VAL \'|\' J  J : VAL '
    
_lr_action_items = {'VAL':([2,6,7,10,16,22,23,27,33,],[3,9,3,13,18,25,18,31,31,]),'[':([0,],[2,]),':':([18,],[22,]),'=':([3,],[6,]),'SEP':([13,],[14,]),')':([30,31,34,],[32,-15,-14,]),',':([4,9,11,19,21,25,26,28,32,],[7,-6,-4,23,-5,-12,-11,-10,-13,]),'|':([31,],[33,]),']':([4,5,9,11,12,21,],[-3,8,-6,-4,-2,-5,]),'>':([19,20,25,26,28,29,32,],[-9,24,-12,-11,-10,-8,-13,]),'$end':([1,8,],[0,-1,]),'NUM':([14,],[15,]),'(':([22,],[27,]),'<':([15,],[16,]),"'":([6,17,24,],[10,21,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'J':([27,33,],[30,34,]),'F':([16,23,],[20,29,]),'B':([2,7,],[5,12,]),'D':([6,],[11,]),'H':([22,],[28,]),'C':([2,7,],[4,4,]),'A':([0,],[1,]),'I':([22,],[26,]),'E':([15,],[17,]),'G':([16,23,],[19,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> A","S'",1,None,None,None),
  ('A -> [ B ]','A',3,'p_A','ETF.py',54),
  ('B -> C , B','B',3,'p_B_1','ETF.py',60),
  ('B -> C','B',1,'p_B_2','ETF.py',65),
  ('C -> VAL = D','C',3,'p_C','ETF.py',70),
  ("D -> ' VAL SEP NUM E '",'D',6,'p_D_1','ETF.py',75),
  ('D -> VAL','D',1,'p_D_2','ETF.py',80),
  ('E -> < F >','E',3,'p_E','ETF.py',85),
  ('F -> G , F','F',3,'p_F_1','ETF.py',90),
  ('F -> G','F',1,'p_F_2','ETF.py',95),
  ('G -> VAL : H','G',3,'p_G','ETF.py',100),
  ('H -> I','H',1,'p_H_1','ETF.py',105),
  ('H -> VAL','H',1,'p_H_2','ETF.py',110),
  ('I -> ( J )','I',3,'p_I','ETF.py',115),
  ('J -> VAL | J','J',3,'p_J_1','ETF.py',120),
  ('J -> VAL','J',1,'p_J_2','ETF.py',125),
]
